### ISSUE TITLE
Gradle compile line for Android Studio Project

### ISSUE THREAD

**Issue by ArjunAchatz-MF** [javagl/JglTF#16]
Most new Android Studio projects use gradle to pull 3rd party libraries, can we get a Gradle compile line for jglTF ??

**Comment by javagl** [comment]
First of all, one **important** note: There currently is a considerable refactoring going on. The current state is in [the 2.0 branch of JglTF](https://github.com/javagl/JglTF/tree/2.0), but this is still pretty much in progress. 

The primary goal of this refactoring is: Support for glTF 2.0! (This isn't trivial, because glTF 1.0 and glTF 2.0 basically have **nothing** in common in this regard...

But another (important) goal of this refactoring is: (Better) Android support. I'd **really** like to bring glTF to Android devices. This has already been brought up a while ago, in https://github.com/javagl/JglTF/issues/4 . And I once tried compiling it for Android, and summarized some sub-tasks in the linked issue. 

But admittedly, the most important tasks are not yet related to the build system, but to the library itself. One it is technically *possible* to compile JglTF for Android, I'll also publish the required build infrastructure. 

Any contributions are welcome (but keep in mind the refactoring, where still a lot of work remains to be done)

**Comment by javagl** [comment]
This is outdated. If there are _specific_ changes that are required for Android support, this can be tracked separately.
