### ISSUE TITLE
Where are we on GlTF v 2.0?

### ISSUE THREAD

**Issue by nbouayad** [javagl/JglTF#18]
I was checking the 2.0 branch, but It does not build.
There are impl-v1 and impl-v2, but model still refers to impl-v1.
Am I missing something?

**Comment by javagl** [comment]
The update is currently in progress. I've been refactoring a lot recently, but still am not sure about an appropriate structure. I even considered dropping glTF 1.0 support, because the structures are just **too** different. But on the other hand, I'll still have to use the `technique`-based approach to somehow emulate the PBR rendering. It's difficult. But I hope that I can bring the 2.0 branch to a state that at least compiles properly.

**Comment by javagl** [comment]
@nbouayad Just a short update: There have been some commits in [the 2.0 branch](https://github.com/javagl/JglTF/tree/2.0). It's still not final, and particularly the main part - namely, the PBR implementation - is still pending. The current plan is to create some infrastructure that examines a glTF 2.0 material, and creates the `Technique`/`Program`/`Shader` instances transparently at runtime. (These classes still existed in 1.0, and will be an extension in 2.0). 

For a first shot, I'd probably try to get it running based on the experimental PBR implementation that I created at https://github.com/javagl/gltfTestModels/blob/master/DamagedHelmetModified/glTF/pbr.frag , but I think that for vertex skinning (and maybe some other features), it might be necessary to actually roll out a full-fledged "Shader Generator" that generates the source code for each `material` *and* model...

**Comment by javagl** [comment]
The current state supports the core features of glTF 2.0, together with a first implementation of PBR in form of an übershader that covers all material properties ( https://github.com/javagl/JglTF/blob/master/jgltf-model/src/main/resources/pbr.frag ). 

The shader will still have to be extended in order to properly support lights and environment maps (right now, there is only one fixed light, which certainly is not appropriate for most scenes...)

This, and some of the "less important" features of glTF 2.0 (e.g. Catmull-Rom-Interpolation for animations) will implemented successively.
