### ISSUE TITLE
Component Type 5125 (UNSIGNED_INT) for V1

### ISSUE THREAD

**Issue by Knacktus** [javagl/JglTF#22]
JglTF\jgltf-impl-v1\src\main\java\de\javagl\jgltf\impl\v1\Accessor.java line 204

```
    public void setComponentType(Integer componentType) {
        if (componentType == null) {
            throw new NullPointerException((("Invalid value for componentType: "+ componentType)+", may not be null"));
        }
        if (((((componentType!= 5120)&&(componentType!= 5121))&&(componentType!= 5122))&&(componentType!= 5123))&&(componentType!= 5126)) {
            throw new IllegalArgumentException((("Invalid value for componentType: "+ componentType)+", valid: [5120, 5121, 5122, 5123, 5126]"));
        }
        this.componentType = componentType;
    }
```

This check doesn't have component type 5125 in the list of allowed types. I have V1 files that I need to convert to V2. Those V1 files work fine with three.js. I don't now it the type 5125 was added in V2 or already valid in V1?

Best regards,

Jan

P.S.: Thanks for the great lib.

**Comment by javagl** [comment]
As noted in the README.md of the `gltf-impl-v1/v2` projects: These classes are auto-generated from the schema. And in glTF 1.0, the component type `GL_UNSIGNED_INT` was not yet allowed: https://github.com/KhronosGroup/glTF/blob/master/specification/1.0/schema/accessor.schema.json#L34 

(This was basically a side-effect of glTF 1.0 targeting WebGL. There, the indices are limited to unsigned short values - at least for the earlier WebGL versions. This restriction will likely be removed soon).

---

Some background: Originally, I thought that auto-generating the classes from the schema might be a good idea, in order to always be sure that the classes perfectly match the specification. And I used these classes everywhere in my implementation. However, when glTF 2.0 was introduced, this turned out to be a horrible idea: They changed all the dictionaries (aka `Map<String, T>` in Java)  to be **arrays** (aka `List<T>` in Java). So despite the *structural* similarities, the `impl-v1` and `impl-v2` classes hardly have anything in common. I tried to create an thin abstraction layer, in form of the `model` library, to cover both versions, but this still may need some work to become a bit more stable. This particularly refers to the parts surrounding the `material` and `technique` concepts, which I'm still trying to get a handle on...

BTW: I also wrote a class that does a (**very** basic) glTF1.0-to-glTF2.0-conversion. (Of course, things like techniques cannot be converted sensibly...). I'll post it here later today, maybe it helps you - not necessarily as a starting point for own work, but rather as a quarry for code snippets that may be required for such a conversion.

**Comment by javagl** [comment]
As mentioned above, here is a snapshot of what I once started to write for converting glTF 1.0 to glTF 2.0. 

Again: 

# This is only a very basic stub

It will certainly not work for all models, but maybe, one day, I can allocate some time for extending it. 

Preferably, it should not be necessary in the future. The best solution would be to load the glTF (1.0) as a "GltfModel", and be able to store it as a glTF (2.0) file. But in any case, there are changes between 1.0 and 2.0 that require some tweaks. Particularly, the materials. The converter currently *tries* to convert the glTF 1.0 `technique` into one that uses the glTF 2.0 `technique-webgl` extension, but that makes limited sense: It is not yet fully specified.

However, maybe someone finds it useful as a preliminary solution for certain (simple) models. There is a `ConverterExample` class included that applies the converter to the "Duck" sample, which basically seems to work, although I have not yet passed the result to the validator...


[jgltf-converter-SNAPSHOT_2017-10-04.zip](https://github.com/javagl/JglTF/files/1357202/jgltf-converter-SNAPSHOT_2017-10-04.zip)

**Comment by javagl** [comment]
Assuming it's OK to close this.
