### ISSUE TITLE
Why not deploy to maven central repo

### ISSUE THREAD

**Issue by powerocean** [javagl/JglTF#24]

**Comment by javagl** [comment]
Of course, it *could* be deployed to Maven Central. I've done this for many other of my projects, but not yet for JglTF.

The main reasons right now are

- I'd like to improve the PBR. The current PBR shader only offers very basic rendering, only one fixed light, no environment lights, and still lacks some other features
- I'd like to tailor the base libraries (`impl`, `model` and `viewer`) so that they work on Android. This may still involve some changes. Also, I only recently started with Android development, at least after I did some basic OpenGL stuff on Android >~5 years ago
- A lack of time. I'm currently drowning in ... (not really "work", but) "other stuff that I have to do or want to do". JglTF is only one of many of my projects.

However, I'll try to schedule an early release of the current state. At least the `impl`- and part of the `model`-classes might already be useful for someone.

**Comment by olomakovskyi** [comment]
Hi, any updates on this? I found this lib very useful but it is not very convenient to use without maven repository.

**Comment by javagl** [comment]
No update yet, and it's somewhat embarrassing, considering that this was already requested last year. But I hope that I can invest more time again for JglTF soon, and one of the first tasks would be to bring the current state into Maven Central. I'll keep you posted.

**Comment by shaileshiyer** [comment]
so is it currently available in the maven repository ? and what all is missing from the jgltf standard 
.

**Comment by javagl** [comment]
No, it is not (yet) available in Maven Central. As soon as it is, I'll drop a note here and close this issue.

**Comment by vipcxj** [comment]
Any plan？ I want to reference this library as dependeny to my project through maven coordinate

**Comment by javagl** [comment]
I'll schedule a release to Maven Central for the holidays

**Comment by javagl** [comment]
Parts of the libraries that had to be refactored for the transition from glTF 1.0 to glTF 2.0 are not yet as mature and stable as I'd like them to be. The PBR- and Android support are still not tackled. At least I recently started creating a `jgltf-model-builder` project that is supposed to support the implementation of converters and the programmatic creation of glTF models. 

So **there will most likely be breaking changes** as soon as I can invest more time here. 

<sup>(And by the way: I'm a freelancer and can shift priorities from my "real" work to my spare time projects. Just contact me at `jobs@javagl.de`)</sup>

However, due to popular demand, the current state of the libraries is now available in Maven Central under the following coordinates:

    <dependency>
        <groupId>de.javagl</groupId>
        <artifactId>jgltf-impl-v1</artifactId>
        <version>2.0.0</version>
    </dependency>
    <dependency>
        <groupId>de.javagl</groupId>
        <artifactId>jgltf-impl-v2</artifactId>
        <version>2.0.0</version>
    </dependency>
    <dependency>
        <groupId>de.javagl</groupId>
        <artifactId>jgltf-impl-v2-technique-webgl</artifactId>
        <version>2.0.0</version>
    </dependency>
    <dependency>
        <groupId>de.javagl</groupId>
        <artifactId>jgltf-model</artifactId>
        <version>2.0.0</version>
    </dependency>
    <dependency>
        <groupId>de.javagl</groupId>
        <artifactId>jgltf-obj</artifactId>
        <version>2.0.0</version>
    </dependency>
    <dependency>
        <groupId>de.javagl</groupId>
        <artifactId>jgltf-validator</artifactId>
        <version>2.0.0</version>
    </dependency>
    <dependency>
        <groupId>de.javagl</groupId>
        <artifactId>jgltf-viewer</artifactId>
        <version>2.0.0</version>
    </dependency>
    <dependency>
        <groupId>de.javagl</groupId>
        <artifactId>jgltf-viewer-jogl</artifactId>
        <version>2.0.0</version>
    </dependency>
    <dependency>
        <groupId>de.javagl</groupId>
        <artifactId>jgltf-viewer-lwjgl</artifactId>
        <version>2.0.0</version>
    </dependency>

(The `jgltf-browser` is a standalone application and not a library. Releases of the browser are occasionally published at https://github.com/javagl/JglTF/releases )
