### ISSUE TITLE
Need help on GLB/gITF parser

### ISSUE THREAD

**Issue by ldkhanh** [javagl/JglTF#35]
Hi,

I'm learning about 3D glTF and GLB format. I would like to build feature to parse meta-data of these file in Java.
Do we have GLB parser to parse meta-data or detect glb, get dimension and others?
I see we have gltf validator in java. Can we convert glb to gltf in java?

Thank you !

Best,
Khanh

**Comment by javagl** [comment]
Sorry for the slow response. 

I assume that this only referring to the *images* that are contained in the GLB. (Otherwise, the MIME type would be [`model/gltf-binary`](https://www.iana.org/assignments/media-types/model/gltf-binary), and the file size would be... well, the file size ;-))

When you read a GLB with JglTF, you obtain a `GtlfModel`, which in turn contains `ImageModel` objects for each image. These contain the MIME type of the image, and the actual image data.

The dimensions of the image (i.e. the size in pixels) is *not* contained in the GLB file. The GLB file only contains the "raw" image data, in PNG or JPG format. So in order to determine the dimensions of the image, one has to *read* this data and create an actual image.

(One reason of why this is not directly part of JglTF is that things are done differently here, depending on whether the library is used in a standard Java Desktop application, or on Android).

However, here is an example that downloads the "BoomBox" example from the Khronos repository and prints information about all the contained images:


    package de.javagl.jgltf.example;
    
    import java.awt.image.BufferedImage;
    import java.io.IOException;
    import java.io.InputStream;
    import java.net.URI;
    import java.nio.ByteBuffer;
    
    import javax.imageio.ImageIO;
    
    import de.javagl.jgltf.model.GltfModel;
    import de.javagl.jgltf.model.ImageModel;
    import de.javagl.jgltf.model.io.Buffers;
    import de.javagl.jgltf.model.io.GltfModelReader;
    
    public class GlbReadingExample
    {
        public static void main(String[] args) throws Exception
        {
            URI uri = new URI("https://raw.githubusercontent.com/KhronosGroup/"
                + "glTF-Sample-Models/master/2.0/BoomBox/glTF-Binary/BoomBox.glb");
            GltfModelReader gltfModelReader = new GltfModelReader();
            
            System.out.println("Reading from " + uri);
            GltfModel gltfModel = gltfModelReader.read(uri);
            
            System.out.println("Images in glTF:");
            for (ImageModel imageModel : gltfModel.getImageModels())
            {
                ByteBuffer imageData = imageModel.getImageData();
                BufferedImage image = readAsBufferedImage(imageData);
    
                System.out.println("URI: " + imageModel.getUri());
                System.out.println("MIME type: " + imageModel.getMimeType());
                System.out.println("File size: " + imageData.capacity());
                System.out.println("Image width: " + image.getWidth());
                System.out.println("Image height: " + image.getWidth());
            }
        }
    
        // A similar function exists, but is not public: In some cases
        // e.g. on Android, "BufferedImage" is not available
        private static BufferedImage readAsBufferedImage(ByteBuffer byteBuffer)
            throws IOException
        {
            try (InputStream inputStream =
                Buffers.createByteBufferInputStream(byteBuffer.slice()))
            {
                return ImageIO.read(inputStream);
            }
        }
    }

The output is

    Reading from https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoomBox/glTF-Binary/BoomBox.glb
    Images in glTF:
    URI: null
    MIME type: image/png
    File size: 3285844
    Image width: 2048
    Image height: 2048
    URI: null
    MIME type: image/png
    File size: 4471451
    Image width: 2048
    Image height: 2048
    URI: null
    MIME type: image/png
    File size: 2845923
    Image width: 2048
    Image height: 2048
    URI: null
    MIME type: image/png
    File size: 132833
    Image width: 2048
    Image height: 2048

Is this what you have been looking for?

**Comment by ldkhanh** [comment]
Hi @javagl,

Great. Thank you so much for your help. This is what I'm looking. I will start learn more about this platform JglTF.

Best,
Khanh
