### ISSUE TITLE
Submit a new release

### ISSUE THREAD

**Issue by jailln** [javagl/JglTF#54]
Hello,

Thanks for this nice tool. I am trying to use it in a maven project but the last release is from 2 years ago and you added more work since then. Would it be possible to publish a new release please ?
I could import it by installing the jar but it gets more complicated when debugging the source code of my project using it :smile: 

Thanks

**Comment by javagl** [comment]
Unfortunately, there have not been sooo significant updates since the release. (Things like auto-generating the base classes from the schema are "details", so to speak - they should be largely backward compatible). I'd really like to make some progress in the "model creation" branch and wrap it up and merge it to master, but ... I'm juggling with priorities. 

However, based on this request, I can increase the priority of an update accordingly. I cannot give an exact timeline, but I might have a _bit_ more time for JglTF in the near future, so ... fingers crossed, maybe I can make some progress.

**Comment by jailln** [comment]
Thanks for your answer :)
There have not been significant modifications since then indeed. Very good news if you find some time to work on this project! I will use the 2.0.0 version until then :)
Cheers
