### ISSUE TITLE
Some fixable bugs and improvements that can be applied

### ISSUE THREAD

**Issue by TimLee9024** [javagl/JglTF#60]
Recently I just finish [porting your work to Minecraft](https://github.com/TimLee9024/MCglTF), almost every feature from glTF spec works great and fine.
During development, I discover some issues and potential improvements in JglTF, but these are quite easy to fix and add.

### 1. MeshModel#getWeights() should pass reference like NodeModel#getWeights()
https://github.com/javagl/JglTF/blob/8b4b15477d4b8971005d76867bda1c377a7a5f2d/jgltf-model/src/main/java/de/javagl/jgltf/model/MeshModel.java#L45
https://github.com/javagl/JglTF/blob/8b4b15477d4b8971005d76867bda1c377a7a5f2d/jgltf-model/src/main/java/de/javagl/jgltf/model/NodeModel.java#L166
https://github.com/javagl/JglTF/blob/8b4b15477d4b8971005d76867bda1c377a7a5f2d/jgltf-viewer/src/main/java/de/javagl/jgltf/viewer/DefaultRenderedGltfModel.java#L760
The `System$arraycopy` is already been used in attributes update command, there is no need to clone array before aquire it.

### 2. AbstractAccessorData#getByteIndex(int elementIndex, int componentIndex) return wrong index if componentType were byte and short, and elementType was not a matrix.
This was discovered when writting my own attributes [unindexer](https://github.com/TimLee9024/MCglTF/blob/83a8578aae849dd5cf3f31e2adbd9399719ba377/src/main/java/com/timlee9024/mcgltf/RenderedGltfModel.java#L2028) for [Mikk tangent generator](https://github.com/jMonkeyEngine/jmonkeyengine/tree/master/jme3-core/src/main/java/com/jme3/util/mikktspace) and flat normal generator.
https://github.com/javagl/JglTF/blob/8b4b15477d4b8971005d76867bda1c377a7a5f2d/jgltf-model/src/main/java/de/javagl/jgltf/model/AbstractAccessorData.java#L147
It seem like you forget to add `else` clause if elementType is not a matrix.

https://github.com/TimLee9024/MCglTF/blob/83a8578aae849dd5cf3f31e2adbd9399719ba377/src/main/java/de/javagl/jgltf/model/AbstractAccessorData.java#L147

### 3. Binary data of .glb should be allocated as direct ByteBuffer
Since I can not find anywhere in your code that convert loaded binary data to direct ByteBuffer before `GltfModel` is created for OpenGL use. I decide to convert them in RawBinaryGltfDataReader V1 and V2.

https://github.com/TimLee9024/MCglTF/commit/cff5cde45691aef1d4f549fbb4ede4099b3e8a41
### 4. Add an abstract getFloat method in AccessorData interface, and return float value from normalized result in AccessorByteData, AccessorShortData, and AccessorIntData.
In [glTF spec](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/Specification.adoc#37-geometry), attributes like `TEXCOORD_n` and `COLOR_n` can be **byte normalized** and **short normalized**, but you will need to convert them to float before processing with Mikk tangent generator and creating attributes update command.
The algorithm for converting integer to float is described as [Normalized Integer](https://www.khronos.org/opengl/wiki/Normalized_Integer) in OpenGL wiki and the following is the implemetation that can be in your code.

[AccessorData](https://github.com/TimLee9024/MCglTF/blob/d9d6c8c5149a2948783bffaf4d16209c088436ee/src/main/java/de/javagl/jgltf/model/AccessorData.java#L91)
``` java
float getFloat(int elementIndex, int componentIndex);
```

[AccessorByteData](https://github.com/TimLee9024/MCglTF/blob/d9d6c8c5149a2948783bffaf4d16209c088436ee/src/main/java/de/javagl/jgltf/model/AccessorByteData.java#L111)
``` java
public float getFloat(int elementIndex, int componentIndex) {
	byte value = get(elementIndex, componentIndex);
	return unsigned ? Byte.toUnsignedInt(value) / (Byte.MAX_VALUE - Byte.MIN_VALUE) : Math.max(value / Byte.MAX_VALUE, -1.0F);
}
```

[AccessorShortData](https://github.com/TimLee9024/MCglTF/blob/d9d6c8c5149a2948783bffaf4d16209c088436ee/src/main/java/de/javagl/jgltf/model/AccessorShortData.java#L113)
``` java
public float getFloat(int elementIndex, int componentIndex) {
	short value = get(elementIndex, componentIndex);
	return unsigned ? Short.toUnsignedInt(value) / (Short.MAX_VALUE - Short.MIN_VALUE) : Math.max(value / Short.MAX_VALUE, -1.0F);
}
```

[AccessorIntData](https://github.com/TimLee9024/MCglTF/blob/d9d6c8c5149a2948783bffaf4d16209c088436ee/src/main/java/de/javagl/jgltf/model/AccessorIntData.java#L113)
``` java
public float getFloat(int elementIndex, int componentIndex) {
	int value = get(elementIndex, componentIndex);
	return unsigned ? Integer.toUnsignedLong(value) / (Integer.MAX_VALUE - Integer.MIN_VALUE) : Math.max(value / Integer.MAX_VALUE, -1.0F);
}
```

[AccessorFloatData](https://github.com/TimLee9024/MCglTF/blob/d9d6c8c5149a2948783bffaf4d16209c088436ee/src/main/java/de/javagl/jgltf/model/AccessorFloatData.java#L96)
``` java
public float getFloat(int elementIndex, int componentIndex) {
	return get(elementIndex, componentIndex);
}
```

**Comment by javagl** [comment]
This is great! I _really_ appreciate this focussed and constructive feedback.

I'll summarize my first thoughts here quickly, and address each of them in more detail ASAP:

---

>  1. MeshModel#getWeights() should pass reference like NodeModel#getWeights()

I _usually_ do not return _references_ in cases like this, because the internal state of an object should be protected:
```
// This will break the internal state, and this 
// should (usually) not be possible:
node.getWeights()[0] = Float.NaN; 
node.getWeights()[1] = Float.NEGATIVE_INFINITY;
node.getWeights()[2] = 0.0f; 
```
But for the `NodeModel`, I'm already returning references, because the alternatives would have been to...

- either return the data as an unmodifiable `List<Float>` or so. This did not seem to make sense for OpenGL interaction (even though one could have considered an unmodifiable direct `FloatBuffer` here). 
- or _always_ return a _copy_ of the array (as it is done in `MeshModel` right now)

But I agree that it makes sense to return a _reference_ in `MeshModel` as well, to be consistent. 

(It's a "breaking change", strictly speaking, but there will be some breaking changes in the next release...)

---

> 2. AbstractAccessorData#getByteIndex(int elementIndex, int componentIndex) return wrong index if componentType were byte and short, and elementType was not a matrix.

From a quick glance, you are right. This special handling for the matrices was added in [a relatively recent commit](https://github.com/javagl/JglTF/commit/6cacec5254d144ddf40cb4a187fab1a9bdd8093b#diff-a62059bb52e9f300889f00276415109ae6a4f4907305825610829b7a3427ec72L146), and the `AccessorDataTests` that have been introduced there did not cover the case that you described. I'll fix this ASAP and extend the test accordingly.


---

> 3. Binary data of .glb should be allocated as direct ByteBuffer

This is the most difficult one. I know that OpenGL-bindings for Java usually need **direct** buffers. And right now, people _could_ work around that by checking 
```
if (buffer.isDirect()) use(buffer);
else use(directCopyOf(buffer));
```
But ... this is inconvenient and cumbersome. On the other hand, I'd hesitate to make a strong guarantee about _which_ buffer is a _direct_ buffer _in general_. The point is, in the following pseudo(!)code:

```
GltfModel modelA = createFrom(directByteBuffer);
GltfModel modelB = createFrom(NONdirectByteBuffer);

ByteBuffer attributeA = modelA.getNode(x).getMesh().getAttribute(y).getData();
ByteBuffer attributeB = modelB.getNode(x).getMesh().getAttribute(y).getData();

// Should I be able to GUARANTEE this here?
assertTrue(attributeA.isDirect());
assertFalse(attributeB.isDirect());
```
Or to put it that way: It's difficult to guarantee that the "directness" of buffers is "transported" through the whole model and all computations....


---

> 4. Add an abstract getFloat method in AccessorData interface, and return float value from normalized result  ....

A first basic support for representing normalized accessors has only been added in [another recent commit](https://github.com/javagl/JglTF/commit/2fbc56ef757b21ad399665003f5d4b9777bd712a). And as the commit message says: This is *"Not deeply integrated and tested yet."*. I already considered some options for adding a convenience method like the `getFloat` that you suggested, and this could certainly make sense. But I'll have to think about some details here. 

For example: I think it should be called `getDequantizedFloat` or so, to make clear that it is not just "the value casted to `float`", but that it really performs the computation that scales the value to the [0,1]/[-1/1] range. Also, I thought about some checks like this:
```
float getDequantizedFloat(...) {
    if (this.isNormalized()) return ...;
    else {
        // Calling this on a non-normalized accessor. 
        // What should happen here? 
        // An error message? 
        // An exception? 
        // Or just cast the actual value to `float`?
    }
}
```
(I think that just casting the value to `float` could make sense, but am not sure...)

---

**Comment by TimLee9024** [comment]
> This is the most difficult one. I know that OpenGL-bindings for Java usually need direct buffers. And right now, people could work around that by checking

Maybe you can just only ensure all of the `ByteBuffer` created from `GltfModelReader`(.glTF, embeded .glTF, and .glb) are direct.

And thank you for your detailed answers about the recent commit in your experimental branch,  I will wait until your next release come up.

**Comment by javagl** [comment]
The first points have been addressed with https://github.com/javagl/JglTF/commit/7ce595c8de434cc7edf5eb91f918e41d6d22a5e3 and https://github.com/javagl/JglTF/commit/6a94c5669a4e9bc8cbc704b22782718c7b3f4c89 

For the `getFloat` method: It could be nice would be to be able to say
`AccessorFloatData f = accessorIntData.dequantize()`
but that ship has sailed. (Nowadays, I'm tending to **ALWAYS** use interfaces, and have **NO** public classes. Lesson learned...)
I'll offer _some_ convenience method like `getFloat`, but am considering different options here.

Regarding the direct buffers: One option to alleviate that would be to start "at the root", and just make sure that data that is read [from the `IO` class](https://github.com/javagl/JglTF/blob/6a94c5669a4e9bc8cbc704b22782718c7b3f4c89/jgltf-model/src/main/java/de/javagl/jgltf/model/io/IO.java#L294) never exists as `byte[]`, but only in `ByteBuffer` in the first place. But here, I also have to look closer at the exact changes that may be necessary.

**Comment by javagl** [comment]
An aside, @TimLee9024 : You pointed to https://github.com/TimLee9024/MCglTF/blob/83a8578aae849dd5cf3f31e2adbd9399719ba377/src/main/java/de/javagl/jgltf/model/AbstractAccessorData.java#L147 in your first post, and I *think* that there's an `else` missing as well, at https://github.com/TimLee9024/MCglTF/blob/83a8578aae849dd5cf3f31e2adbd9399719ba377/src/main/java/de/javagl/jgltf/model/AbstractAccessorData.java#L161 (but haven't verified yet)

**Comment by javagl** [comment]
Again, thanks for this feedback. The first points have been addressed. The last two points are now tracked in dedicated issues:

- https://github.com/javagl/JglTF/issues/73
- https://github.com/javagl/JglTF/issues/74

So I'll close this one.
