### ISSUE TITLE
Writing/Reading a mesh format that defines a color/texture per triangle instead of per vertex

### ISSUE THREAD

**Issue by Suicolen** [javagl/JglTF#64]
I'm looking for the best possible option to convert a custom mesh format to glTF (and vice versa) that defines solid colors and textures per triangle.

In case this helps, here's an overview of my format:
- Vertices array (Vec3f)
- Indices array (Vec3f)
- Triangle/Face colors array (Integer, 24-bit RGB values) - This is per triangle
- Texture Ids array (Integer) - This is per triangle
- Triangle Flags array(Integer, determines whether to use a color from the colors or textures array) - This is per triangle
- Texture coordinate arrays (float[][] uCoordinates, float[][] vCoordinates) - Per triangle, accessed like this:
```
// length 3, stores u/v coordinates for each vertex of that triangle
float[] u = uCoordinates[triangleIndex]
float[] v = vCoordinates[triangleIndex]
```

My ideas so far:
1) Possibly the worst one: From the glTF specification i found that you can specify a vertex color, so my idea was to simply specify for each triangle the same vertex color, that did not work out well as blender seems to be interpolating vertex colors even if normals are not defined(unless i did something wrong myself)
2) Convert all of the solid colors and textures that the mesh uses into one single texture and compute appropriate texture coordinates (this process should also be reversible however the main problem i have with it is that ideally i'd want to define per face colors/textures so that individual faces can be painted with a specific color/texture easily)
3) Create multiple MeshPrimitive's, group by material (i.e for each unique material in the mesh create a MeshPrimitive) however that'd still limit editing individual faces i believe.
4) another possibly bad solution: Create one mesh primitive per triangle

My goal is to export the custom mesh format to glTF, then import that in blender for easy editing (the geometry, the materials in a way that allows u to edit them per face) and i also want to be able to take the mesh edited in blender(exported as glTF) and convert that back to the custom format.
Any suggestions would be greatly appreciated (if i didn't clarify some parts well enough, please let me know)

Note: I have done this before usong different formats (MQO and OBJ) where i defined the data for each triangle like this(MQO example):
```
// faces followed by the number of faces/triangles in the mesh
faces 153 {
  // component count of vertex(it's a triangle so it's 3 here), The vertex indices (in the vertex array, defined earlier in the file) Material index (defined earlier in the file), Texture coordinates for that triangle
  3 V(18 13 12) M(256) UV(0.078947365 -0.045834996 0.05263158 0.4348346 0.18421052 -0.023515346)
  etc
}
```
but now i need to somehow achieve this with glTF (as the other formats i've used so far don't support skeletal animation) and I picked glTF because it has really good specification/documentation and there's this great library for it to deal with glTF reading/writing in java

**Comment by Suicolen** [comment]
> 

First of all, i appreciate such a quick and detailed reply with examples(just a hour after my question, that is actually impressive)
as for the first issue with interpolating that i asked about, it all makes sense now after ur explanation.

(oh also MQO is not really a known format, i should've mentioned that or just included an OBJ example instead)

About the OBJ, this is exactly what i did and it was quite flexible.
> When converting an OBJ file into a glTF asset, this has to be taken into account: When there are faces that share vertices with different properties (texture coordinates or normals), then these vertices have to be duplicated. In fact, this has to be done even for just rendering an OBJ. (That's what [ObjUtils::makePropertiesUnique](https://github.com/javagl/Obj/blob/59b0c3266fcef8c07f0d33bb7821d4472632e9a2/src/main/java/de/javagl/obj/ObjUtils.java#L466) from my Obj library is doing...)
thanks for mentioning this, as i was not aware that's what had to be done when converting OBJ to glTF

To the last option, it indeed does seem like that is possibly the best option for what i want to achieve, however now im having seconds thought, the meshes don't have many triangles (1000 on average, never above 7000-8000) but im starting to ask myself 'is it really worth it' because it seems like blender isn't ideal for painting like this so i might consider another route where i do the geometry, rigging, animations in blender and after that is done i use a different tool to do the painting (possibly my own as i have actually made a material editor(along with some other things) for that specific model format & the engine that uses the model format)

This does seem like the better option as the main reason i want to have the conversion to glTF and vice versa is for rigging & creating animations in blender.

as for why i wouldn't just make the custom engine support a format like glTF for example since it wouldn't be that much work is because im making an open source tool for a modding community and i don't want the users to make engine changes(it's actually a bit more complicated than that but it's not really important right now, simply put i just want them to be able to use the tool out of the box without needing to make a bunch of engine changes)

Back to my idea of not doing materials in blender:
If i do however export a mesh (Custom format -> glTF) and the only use case is to just create animations for an existing mesh(so no geometry or material changes in blender, just animations) then I'd want to preserve the existing materials, i'm not quite sure how to do that yet as i haven't looked into it however if i remember correctly glTF supports 'extras' so perhaps i could just write the colors there (in the format of triangleIndex -> material) for example (if there are better options, i'd be happy to hear them)

**Comment by javagl** [comment]
I'm not deeply familiar with Blender in general, or the Blender glTF plugin. But I just did a quick test of assigning different materials to the faces of a cube, and the result is indeed that each material is exported as one mesh primitive. So the criterion for _grouping_ faces into mesh primitives seems to be the _material_ that is assigned to them. 

Now I'm actually somewhat curious about how "smart" Blender is during that export, and I'm tempted to try and come up with different configurations and corner cases. But that may not be crucially important right now.

But two things that I _did_ try out: 

- The grouping happens _by material_, and not _by material properties_ (that makes sense - even if two materials are 'equal' in terms of their properties, they should still be retaines as _two different materials_)
- Initially, when moving one corner of the cube, then you can see that the mesh is "connected". Referring to the example above: When moving vertex '1', then this is the _same_ vertex for triangles `0 1 2` and `1 3 2`. But when exporting the mesh as glTF, and re-importing it, these are separate vertices. So Blender does internally "duplicate" the vertices, so that they may have different colors. 

So depending on your desired workflow, then option 3. 

> Create multiple MeshPrimitive's, group by material (i.e for each unique material in the mesh create a MeshPrimitive) however that'd still limit editing individual faces i believe.

may actually work pretty well: When you have an object with 100 red faces and 100 blue faces (i.e. two mesh primitives, grouped by material), and edit the mesh in blender, and assign the 'blue' material to one of the formerly 'red' faces, then Blender seems to export that as an asset where this triangle now belongs to the 'blue' object.

Things might become a bit more tricky for texture coordinates, though. How do you determine sensible texture coordinates for a triangle that is floating somewhere in space, with arbitrary shape? But regardless of the texture coordinate _values_: I _assume_ that when a group of triangles uses the same material, then they will be grouped into one mesh primitive in any case.

**Comment by Suicolen** [comment]
Yeah, i am also not sure how I'd do texture coordinates in this case. I did think about it for a little and it actually seems pretty complicated (assuming it's even possible) so im not sure if it's even worth all the effort, and maybe my last option where i simply do not include the materials for the mesh (but still preserve them somewhere, if the mesh is exported just for animation) and only use glTF/blender for making the mesh itself(geometry, rigging) and animations is actually the way to go, altho i'll still try other ways before i go that route.
