### ISSUE TITLE
Unsupported textures file formats: DDS

### ISSUE THREAD

**Issue by Sevelantis** [javagl/JglTF#65]
Hello,
I emailed Marco Hutter, the JavaGL author with a question about the DDS format support, since I needed it in my tool. Maybe someone reading this would find it helpful. Next time I will just open an issue initially - this is my first :)

[What is .dds file format?](https://fileinfo.com/extension/dds#:~:text=A%20DDS%20file%20is%20a,photos%20and%20Windows%20desktop%20backgrounds)

**Issue: DDS is unsupported, jgltf-model version 2.0.1**

- [Context] - The [javagl/JglTF](https://github.com/javagl/JglTF) library of yours, could be pricelessly useful in my non-profit small-scope project. Project’s main goal is to convert 3D models OBJ files to GLB format automatically as a part of website functionality. Your tool is the best possible choice for this task - it works perfectly for PNG and JPEG textures. Although many computer games use DDS format files. The DDS makes it possible to reduce the amount of memory that textures use by lowering the quality a little.
t file takes less space than actual “EMBEDDED” option. The following error stack trace is being printed:

 - [Error] - java.lang.IllegalArgumentException: Invalid value for mimeType: image/dds, valid: ["image/jpeg", "image/png"]
	at de.javagl.jgltf.impl.v2.Image.setMimeType(Image.java:81)
	at de.javagl.jgltf.model.io.v2.BinaryAssetCreatorV2.create(BinaryAssetCreatorV2.java:169)
	at de.javagl.jgltf.model.io.v2.GltfModelWriterV2.writeBinary(GltfModelWriterV2.java:88)
	at de.javagl.jgltf.model.io.GltfModelWriter.writeBinary(GltfModelWriter.java:148)
	at de.javagl.jgltf.model.io.GltfModelWriter.writeBinary(GltfModelWriter.java:120)

 - [Conclusion] - It looks like the class “MimeTypes” does not support the DDS format, as well as all dependency classes, such as “BinaryAssetCreatorV2”.
Is there anything you could do in order to add the DDS format support to your https://github.com/javagl/JglTF library?
I will be happy to provide more details and help you in any further process — feel free to ask if there is anything you would like to know about the issue.

**Marcos (JavaGL/JglTF author) response in short:**

- "_... I'm aware of the problem that you described. ..._"
- "_...And in fact, I already removed this check a few months ago: [commit](https://github.com/javagl/JglTF/commit/4024e39cc7b18add4b90caffcaae24956ecf117e#diff-dc0bbd04ebf541fdfdfa3ca925f2d20ed64de086457ae9a6cdb0ccdd1afed2dbL82) . So in the version of JglTF that can currently be found in the repository, the problem should already be solved. ..._"
- "_... The updated version is NOT yet published in Maven Central. ..._"

----------
@javagl Thank you for your fast and professional response. If possible, please also let us know when the version 2.0.2 of jgltf-model dependency is published to Maven repo.

**Comment by Sevelantis** [comment]
@javagl When will the updated version be published in Maven Central?

**Comment by javagl** [comment]
I just released `2.0.2` and it should be available in Maven Central soon. 

I've been hesitating a bit, because there are some changes that are _breaking_ changes, and I'm not keeping track of these as diligently as I should, and there are a few things "in flight" which I'd like to get into a release soon, but ... after all, this is just a spare-time project, so I probably _have_ to shrug off some of my personal concerns here.

I'll close this one for now, assuming that it is resolved. 

If you encounter any difficulties with that release, they can be tracked in dedicated issues.

**Comment by javagl** [comment]
Update: The latest version is 2.0.3 (sorry for that hiccup)

**Comment by Sevelantis** [comment]
Thank you very much!

Your code is now allowing ".dds" extensions to process, however (correct me if i'm wrong), it turns out that GLTF might not support the DDS fileformat at all.
I am simply trying to convert OBJ to JGLTF using Java.

On the whole GitHub, from my research, there is just one project that addresses such issue. There is a converter created by @oguzhancevik, which uses your JglTF dependency as a core. I already have created an issue in owner's repository, but, as I said before GLTF might not actually support DDS at all. 

I provide a link regarding the issue: https://github.com/oguzhancevik/obj2gltf/issues/3

I am posting this info here just for you to know that the issue still exist, but it turns out that there is another source of it that we didn't expect earlier. Unfortunately I still have no idea how to make the converter to actually start working.

https://github.com/oguzhancevik/obj2gltf/issues/3

**Comment by javagl** [comment]
The original error here (i.e. the `IllegalArgumentException`) was indeed an error in this library. There are some technical details that I could go into, but I'll try to respond on a more general level. This is, in part, a response to your question in the other project. But since the other project is simply a copy or large parts of https://github.com/javagl/JglTF/tree/master/jgltf-obj (violating the copyright), I'll reply here.

By default, glTF only supports JPG and PNG. There are many reasons for that. An important one is that glTF is often used in web-based viewers, and JPG and PNG are natively and automatically supported there. Another reason is rather an "indirect" one - namely the question: Which image formats from https://en.wikipedia.org/wiki/Image_file_format should be supported in glTF? When something like DDS is allowed in glTF, then _each and every glTF viewer_ will have to implement a DDS loader. 

A glTF asset should be _portable_, and it should be possible to view it _everywhere_. Hence the claim that glTF is supposed to be "The JPG of 3D". Limiting the image formats to JPG and PNG is one important precondition for that. Otherwise, you'd regularly receive error messages like: "Sorry, you're using some obscure format there that I can not load".

Of course, there are also reasons why somebody might want to use a different image format. And it is possible to _extend_ glTF so that additional image formats are supported. I could explain some of the technical details behind the extension mechanism in general, but will try to keep this focussed on one question from the linked issue:

> Check out the example extension: https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/MSFT_texture_dds/README.md but I am struggling with implementing this into your code, since it's not clear to me how am I able to implement it. Maybe I should add those JSON lines into every single DDS file, or maybe to the very top of the output GLTF file? Maybe somehow set the flags? How? And maybe you would be able to help..

Usually, a texture in glTF is defined like this:
```
    "textures": [
        {
            "sampler": 0,
            "source": 0
        }
    ],
    "images": [
        {
            "uri": "DuckCM.png"
        }
    ],
```
And the image `uri` can point to a PNG or JPG file. 

When using an extension like the `MSFT_texture_dds` extension, then you can define the texture like this:
```
"textures": [
    {
        "source": 0,
        "extensions": {
            "MSFT_texture_dds": {
                "source": 1
            }
        }
    }
],
"images": [
    {
        "uri": "DuckCM.png"
    },
    {
        "uri": "DuckCM.dds"
    }
]
```
This means that you are then allowed to let the `uri` point to DDS files.

(You'll also have to add the string `MSFT_texture_dds` to `extensionsUsed` - again, I'm skipping some details here).

**But**... this extension also has to be supported by a viewer. When a viewer finds this extension, and does not know how to load DDS files, then it will simply not work. And there are probably _very_ few viewers that _can_ load DDS files, and thefore, very few viewers that support this extension.

---

Depending on your goal, there are different possibilities:

- It could be possible to recognize DDS files, and writes glTF assets that contain the `MSFT_texture_dds` extension. But you'll probably not find many viewers that then can _load_ and _display_ these glTF files...
- It could make more sense to take the input DDS files, and convert them to PNG or JPG, which can then directly be used for the glTF asset.

Both approaches would require an update of `obj2gltf` or https://github.com/javagl/JglTF/tree/master/jgltf-obj . In order to convert a DDS file into PNG, it would be necessary to integrate some Java-based DDS loader library (and I don't know whether there is a "good" one).
