### ISSUE TITLE
A second GltfModelReader.read(uri) method could use a Path argument instead of an URI

### ISSUE THREAD

**Issue by YvesBoyadjian** [javagl/JglTF#66]
I have tried reading a gltf directly from a zip file, and it did not worked, because URI does not handle well files in ZIP.
Making a second method "public GltfModel read(Path uri)" (And the corresponding called methods) worked well with the ZIP file (And also with the unzipped directory structure), because the Path class is more powerful than the URI class
However, I had to set Java language level to 11 in order to use "Path.of(uri)" in "IO.makeAbsolute(Path baseUri, String uriString)" method: 

    public static Path makeAbsolute(Path baseUri, String uriString)
            throws IOException
    {
        try
        {
            String escapedUriString = uriString.replaceAll(" ", "%20");
            URI uri = new URI(escapedUriString);
            if (uri.isAbsolute())
            {
                return Path.of(uri);
            }
            return baseUri.resolve(escapedUriString);
        }
        catch (URISyntaxException e)
        {
            throw new IOException("Invalid URI string: " + uriString, e);
        }
    }

But there is maybe another solution for this method suitable for Java 7 or 8

**Comment by javagl** [comment]
I'll have to look closer at the particular use case of reading a model directly from a ZIP file. (Maybe you can provide some "stub" code, just a short `main` function with the intended workflow, so that I get it right). 

For now, I have to ask for confirmation at a very high-level point: I assume that a call like `reader.read(yourPath.toUri());` (using [`toUri`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#toUri--) does _not_ work for you, is that correct? (If so: What error does this cause?)

More generally, I'm a bit on the fence with _which_ signatures a `read` method should have. It may read from a `URI`, `File`, `Path`, `InputStream`, `ByteBuffer`, `byte[]` array (for "text" data, it may also be a `Reader`, or even a `String`...). On the one hand, it could be convenient to offer _all_ these methods. On the other hand, there are often simple conversions from one argument type to another. For example, I could offer `read(File)` and `read(Path)`, or only one of them, because the caller can trivially call it as `read(file.toPath())` or `read(path.toFile())`, respectively. In that sense, I try to offer the _most generic_ signature. (And here, I thought this was `URI`, but maybe it does not cover the ZIP-file use case that you mentioned...)

**Comment by YvesBoyadjian** [comment]
Yes, it is correct, "reader.read(yourPath.toUri());" does not work in my case. The error is: 

java.lang.NullPointerException: Cannot invoke "String.endsWith(String)" because the return value of "java.net.URI.getPath()" is null
	at de.javagl.jgltf.model.io.IO.getParent(IO.java:106)
	at de.javagl.jgltf.model.io.GltfAssetReader.read(GltfAssetReader.java:99)
	at de.javagl.jgltf.model.io.GltfModelReader.read(GltfModelReader.java:83)

Here is the used code : 

    String filename = "C:\Users\boyadjian\Downloads\hi-tec_mountain_boots_high_poly (1).zip";
    Path filePath = null;
    try {
        filePath = Paths.get(filename);
    } catch( InvalidPathException e) {
        return;
    }
    FileSystem fs = FileSystems.newFileSystem(filePath,(ClassLoader)null);

    for (Path root : fs.getRootDirectories()) {
          Path gltf = findFileWithExtension(root,".gltf",true); // Recursive method to find the gltf file in zip
          if (gltf != null) {
              URI gltfURI = gltf.toUri();
              GltfModelReader reader = new GltfModelReader();
              GltfModel gltfModel = reader.read(gltfURI);    // Throws the NullPointerException                        
              return;
         }
     }

I found also this article, which was helpful: 
[https://stackoverflow.com/questions/27845223/whats-the-difference-between-a-resource-uri-url-path-and-file-in-java](url)

**Comment by javagl** [comment]
The first part of the error could be solved by a small change in the `IO#getParent` function: Instead of using `uri.getPath()`, it could just use `uri.toString()` (at least, from my first, basic test - I should probably test it more thoroughly...). With this change, I managed to read a full GLB file directly from a JAR/ZIP.

But... for a glTF file, there will be difficulties later. When reading the glTF file, it may try to load external resources, like an image or the `.bin` file with the binary data. These resources have to be resolved against a base URL. And in the case of the glTF asset being contained in a JAR file, this raises some questions. The URI of the glTF may be something like
`jar:file:///C:/Data/Archive.zip!/directory/Example.gltf`
Resolving anything against that URI will - as far as I can tell - _not_ resolve to something _inside_ of the JAR file.

Right now, I don't have an idea about how resources could sensibly be resolved within that file.

The naive approach would be to "keep the full path", and say that for 
`jar:file:///C:/Data/Archive.zip!/directory/Example.gltf`
the URI `buffer.bin` should resolve to 
`jar:file:///C:/Data/Archive.zip!/directory/buffer.bin`
but I'd veeery carefully have to analyze whether this is even remotely in line with the spec, or whether it could cause trouble somewhere else...

**Comment by YvesBoyadjian** [comment]
Yes, the problem is not solvable for zip/jar with URI, because there is no sufficient information in this object.
On the contrary, when using Path, for example in case of zip file, object is a "ZipPath", so it contains all necessary information to navigate, for example getting parent.

For my usage, I have doubled all methods using an URI with the equivalent using a Path, and it has solved the problem

**Comment by YvesBoyadjian** [comment]
Here is the PR. I have just added the corresponding methods, in order to keep backward compatibility, and avoid possible regressions
For the question of reading from a zip, it allows to keep downloaded zip files on sketchfab, by example, "as is" to be used as assets in video game

**Comment by javagl** [comment]
Despite some hesitation, and although I'm _usually_ following the mantra "When in doubt, leave it out", the new functions are now part of version 2.0.2

**Comment by javagl** [comment]
Update: The latest version is 2.0.3
