### ISSUE TITLE
Please make latest gltf-browser jar

### ISSUE THREAD

**Issue by cx20** [javagl/JglTF#8]
I tried gltf-browser jar in the following folder, but I could not load the sample model.
https://github.com/javagl/JglTF/releases

I think it is due to old sampleModels.properties in jar.
Please make latest gltf-browser jar

**Comment by javagl** [comment]
That's right: The path to the sample models had changed. This was fixed in https://github.com/javagl/JglTF/commit/bd4d3a8b6a231ff5988a4ad45b55706b4ce424f2 . 

This could also have been fixed locally and manually by editing the properties file in the JAR. But there have been several other updates since the last release - aiming at glTF 1.1 compatibility, the `technique.states` handling and general improvements and bugfixes. 

So a new **preview release** has been uploaded at https://github.com/javagl/JglTF/releases/tag/v0.0.0-alpha04

If there are any problems with this release, they can be discussed in dedicated issues, so I'll close this one for now. (It can be reopened when it's time for another update)

**Comment by cx20** [comment]
Thank you for uploading a latest jar.
