### ISSUE TITLE
How about adding gltfTutorialModels to gltf-browser's menu?

### ISSUE THREAD

**Issue by cx20** [javagl/JglTF#9]
I think that it is better if gltfTutorialModels is in the menu of gltf-browser.

https://github.com/javagl/gltfTutorialModels

**Comment by javagl** [comment]
Yes, good point. The current menu entry with the sample models was just intended as a "convenience functionality", and it is implemented a bit.... ehrm... pragmatically. 

But one could consider different improvements and extensions here: 

First, it might be helpful to at least allow setting the "base path" of the samples manually - for example, by giving it as an optional command line parameter. I noticed that this when I wanted to let the menu contain the sample models *from my local hard drive*, for tests.

Alternatively, one could add the option to specify the [sampleModels.properties](https://github.com/javagl/JglTF/blob/master/jgltf-browser/src/main/resources/sampleModels.properties) file at the command line.

In general, it could be helpful to make the inclusion of other sample model directories more versatile and generic Having to create a new release only because one sample model was added is obviously not reasonable. (But letting the program "explore" the given directory, i.e. search for subdirectories, would require parsing the .MD file and **lots** of guesswork, so this could be fiddly...)

I'll think about the options here. Any ideas or suggestions for how this could be generalized would be welcome. 

(If I don't come up with a "nice" solution soon, I'd first add a second menu with the Tutorial Models, based on the current structure, but would prefer a more sustainable and generic solution in the long run)

**Comment by cx20** [comment]
Thank you for considering.

I think the option to specify the sampleModels.properties file on the command line is good idea.
It is difficult for ordinary people to change or compile the configuration file in the jar file.

**Comment by javagl** [comment]
I did some refactoring regarding the handling of the sample models and the menu.

First of all, the sample models structure is now no longer specified as a `.properties` file, but as a file that contains the menu structure as JSON (see [sampleModels.config](https://github.com/javagl/JglTF/blob/16cccc61f65ac7296fb46c2088ebd521e3cb7b8e/jgltf-browser/src/main/resources/sampleModels.config)). And although the JSON is more elaborate and not so convenient to edit manually, I think it is a reasonable trade-off: The structure of the menu may be nested, like

    Samples
        Khronos
            1.0
                Box
                    glTF
                    glTF-Embedded
                    ...
                Duck
                    ...
            1.1
                ...
        Tutorial
            Triangle
                glTF 
                ...

and specifying something like this as a properties file does not make any sense either.

---

The behavior regarding the source of this menu structure is now as follows:

- By default, the application checks for a file called `sampleModels.config` in the same directory as the JAR. **If** this file exists, it tries to load the menu structure from that. This is intended to allow "overriding" the contents of the JAR more easily: One just has to create this file, but not spcify any command line parameters.
- If there is *no* `sampleModels.config` file in the current directory, then the `sampleModels.config` from inside the JAR is loaded. This contains the Khronos Sample models in version 1.0, and now also the Tutorial sample models.
- Alternatively, one can specify the sample model menu files. Using the command line parameter `-sampleModels`, one can give a list of config files that will be converted into menus:

      java -jar jgltf-browser.jar -sampleModels=myLocalOnes.config,someAdditionalOnes.config

    (the parameter has to be given *without spaces*, but accepts a list of `,` comma-separated file names)

--- 

What concerns be a bit here is the following: Allowing the user to create a file with information about the sample models that appear in the menu implies that there is a certain **file format** involved. People might create such a file, and *expect* that the same file will work with the next verison as well. However, I hope that the version number (0.0.0) and the statements in the README that say that *"These libraries are still subject to change"* make clear that a strict backward compatibility cannot be guaranteed.

**Comment by javagl** [comment]
Although there have been renamings of two of the tutorial models in the meantime, the basic functionality is integrated, and I'll close this one. The updated menu will be part of the next preview release, which I'll probably create in the next days.
