### ISSUE TITLE
Help with rendering/loading gltf model with gltf-model

### ISSUE THREAD

**Issue by RexBluefox** [javagl/JglTF#96]
Hi. I am trying to make a gltf model viewer for minecraft with a fabric mod for 1.20.2.
So far i got he model loading working but when trying to render it it results in a mess of triangles.

This is my code:
```java
File modDirectory = FabricLoader.getInstance().getModContainer(MOD_ID).get().getRootPath().toFile();
File file = new File(modDirectory, "assets/chimera-client/maxwell.gltf");
try {
    FileInputStream fileInputStream = new FileInputStream(file.getPath());
    GltfModelReader reader = new GltfModelReader();
    GltfModel model = reader.read(file.toPath());
    List<MeshModel> meshes = model.getMeshModels();
    Map<String,List<Vector3i>> meshs= new HashMap<>();
    for (MeshModel mesh : meshes) {
        List<Vector3i> vertices = new ArrayList<>();
        for (MeshPrimitiveModel meshPrimitiveModel : mesh.getMeshPrimitiveModels()) {
            Map<String, AccessorModel> attributes = meshPrimitiveModel.getAttributes();
            for (int i = 0; i < attributes.get("POSITION").getBufferViewModel().getBufferModel().getBufferData().limit()/3; i++) {
                int x = attributes.get("POSITION").getBufferViewModel().getBufferModel().getBufferData().get(i);
                int y = attributes.get("POSITION").getBufferViewModel().getBufferModel().getBufferData().get(i+1);
                int z = attributes.get("POSITION").getBufferViewModel().getBufferModel().getBufferData().get(i+2);
                vertices.add(new Vector3i(x,y,z));
            }
        }
        meshs.put(mesh.getName(),vertices);
    }

    DrawContext drawContext = event.drawContext;
    Tessellator tessellator = RenderSystem.renderThreadTesselator();
    BufferBuilder bufferBuilder = tessellator.getBuffer();
    MatrixStack matrixStack = drawContext.getMatrices();
    matrixStack.push();
    Matrix4f matrix = matrixStack.peek().getPositionMatrix();
    RenderSystem.enableDepthTest();
    RenderSystem.setShaderColor(1.0f, 1.0f, 1.0f, 1.0f);
    RenderSystem.setShader(GameRenderer::getPositionColorProgram);
    bufferBuilder.begin(VertexFormat.DrawMode.TRIANGLE_STRIP, VertexFormats.POSITION_COLOR);
    for (Vector3i vector : meshs.get("whiskers")) {
        bufferBuilder.vertex(matrix,vector.x,vector.y,vector.z).color(ColorHolder.random().getARGB()).next();
    }
    tessellator.draw();
    matrixStack.pop();
```
this is what the mess looks like:
![image](https://github.com/javagl/JglTF/assets/53141624/58429766-4315-4dec-81c1-258b9e0c24ac)

this is what it should look like (or for now just the whiskers):
![image](https://github.com/javagl/JglTF/assets/53141624/55c74d79-d815-4dc9-9a96-2de4dced0c22)

Is the way i´m getting the vertices correct or is it that there is my mistake?

**Comment by javagl** [comment]
A tuxedo cat 🤵 😸 

You might want to have another look at the ["Buffers, BufferViews, and Accessors" section of the glTF tutorial](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_005_BuffersBufferViewsAccessors.md). 

An attempt to summarize the main points here:

- An accessor provides access to a _part_ of a buffer view. 
- A buffer view provides acccess to a _part_ of a buffer.  
- The accessor also provides the _type_ information - namely, whether the buffer contains `float` or `int` values, for example. 

With a line like
`attributes.get("POSITION").getBufferViewModel().getBufferModel().getBufferData().get(i);`
you are drilling through the whole structure and accessing the "raw" buffer data (at indices that do not make sense), without interpreting it properly (based on the type information).

JglTF offers some convenience classes for accessing accessor data - and ... coincidentally, the main class here is called `AccessorData`. You can obtain an `AccessorData` from an `AccessorModel`, with
`AccessorData accessorData = accessorModel.getAccessorData();`
The `AccessorData` may have different types, and depending on the result of `getComponentType`, it can be cast into one of these specific types.

## Note:

I don't know the classes that you are using there. For example, I don't know what a `Tessellator` does here, exactly. But I saw that part with `VertexFormat.DrawMode.TRIANGLE_STRIP` and should probably mention that this is likely not correct. You'll probably have to use a draw mode that depends on the value that is returned by `meshPrimitiveModel.getMode()`, and which can be one of the "common" OpenGL triangle modes, which mainly correspond to things like https://maven.fabricmc.net/docs/yarn-21w05b+build.11/net/minecraft/client/render/VertexFormat.DrawMode.html 

However, here is an example that reads a GLB file (just the "Duck.glb" sample model, from a local path), and that prints all positions and triangle indices (knowing that it _does_ use the mode `TRIANGLES`...): 

```
package de.javagl.jgltf.example;

import java.nio.file.Paths;
import java.util.List;
import java.util.Map;

import de.javagl.jgltf.model.AccessorByteData;
import de.javagl.jgltf.model.AccessorData;
import de.javagl.jgltf.model.AccessorFloatData;
import de.javagl.jgltf.model.AccessorIntData;
import de.javagl.jgltf.model.AccessorModel;
import de.javagl.jgltf.model.AccessorShortData;
import de.javagl.jgltf.model.GltfModel;
import de.javagl.jgltf.model.MeshModel;
import de.javagl.jgltf.model.MeshPrimitiveModel;
import de.javagl.jgltf.model.io.GltfModelReader;

public class GltfModelExample_Issue96
{
    public static void main(String[] args) throws Exception
    {
        GltfModelReader gltfModelReader = new GltfModelReader();
        GltfModel gltfModel =
            gltfModelReader.read(Paths.get("./data/Duck.glb"));

        List<MeshModel> meshModels = gltfModel.getMeshModels();
        for (MeshModel meshModel : meshModels)
        {
            List<MeshPrimitiveModel> meshPrimitiveModels =
                meshModel.getMeshPrimitiveModels();
            for (MeshPrimitiveModel meshPrimitiveModel : meshPrimitiveModels)
            {
                printData(meshPrimitiveModel);
            }
        }
    }

    private static void printData(MeshPrimitiveModel meshPrimitiveModel)
    {
        
        Map<String, AccessorModel> attributes =
            meshPrimitiveModel.getAttributes();

        AccessorModel positionsAccessorModel = attributes.get("POSITION");
        AccessorData positionsAccessorData =
            positionsAccessorModel.getAccessorData();

        // The POSITIONS are assumed to be "VEC3 / float" data here:
        AccessorFloatData positionsData =
            (AccessorFloatData) positionsAccessorData;
        int numPositions = positionsData.getNumElements();
        for (int p = 0; p < numPositions; p++)
        {
            float x = positionsData.get(p, 0);
            float y = positionsData.get(p, 1);
            float z = positionsData.get(p, 2);
            System.out
                .println("Vertex " + p + " is at " + x + " " + y + " " + z);
        }

        AccessorModel indicesAccessorModel = meshPrimitiveModel.getIndices();
        if (indicesAccessorModel != null)
        {
            int indices[] = getIndicesAsIntArray(indicesAccessorModel);
            int numTriangles = indices.length / 3;
            for (int t = 0; t < numTriangles; t++)
            {
                int v0 = indices[t * 3 + 0];
                int v1 = indices[t * 3 + 1];
                int v2 = indices[t * 3 + 2];
                System.out.println("Triangle " + t + " has vertex indices " + v0
                    + " " + v1 + " " + v2);
            }
        }
    }

    private static int[] getIndicesAsIntArray(AccessorModel accessorModel)
    {
        AccessorData accessorData = accessorModel.getAccessorData();
        int numElements = accessorData.getNumElements();
        int indices[] = new int[numElements];
        if (accessorData.getComponentType() == int.class)
        {
            AccessorIntData indicesData = (AccessorIntData) accessorData;
            for (int i = 0; i < numElements; i++)
            {
                indices[i] = indicesData.get(i);
            }
            return indices;
        }
        if (accessorData.getComponentType() == short.class)
        {
            AccessorShortData indicesData = (AccessorShortData) accessorData;
            for (int i = 0; i < numElements; i++)
            {
                indices[i] = indicesData.get(i);
            }
            return indices;
        }
        if (accessorData.getComponentType() == byte.class)
        {
            AccessorByteData indicesData = (AccessorByteData) accessorData;
            for (int i = 0; i < numElements; i++)
            {
                indices[i] = indicesData.get(i);
            }
            return indices;
        }
        // Should never happen for valid indices:
        return null;

    }

}
```

In order to properly display that cat, you'll also have to read the textures and the texture coordinates, but ... one step after another.

**Comment by RexBluefox** [comment]
ok. thanks for the quick response. ill take a look a the documentation you sent and also your code.
i changed the model that is loaded from the duck to the cat and all the vertices have coordinates at the 2nd decimal point or even less. is that normal? ill ignore that for now.
i will come back to you with any further issues 👍🏻

**Comment by javagl** [comment]
> i changed the model that is loaded from the duck to the cat and all the vertices have coordinates at the 2nd decimal point or even less. is that normal?

The vertex coordinates are only the vertex coordinates that are stored in the accessor. They will still be affected by the transforms of the nodes that refer to the respective mesh. For example, a vertex coordinate (1,2,3) may be part of a mesh that is attached to a node that has a `translation` of `10,20,30`, and the vertex will end up at (11,22,33). It may also be attached to a node that has a `scale` of `0.1,0.1,0.1`, so that the vertex will end up at (0.1, 0.2, 0.3). 

If your goal is to write a full-fledged "glTF renderer in Minecraft", then you'll have to invest **a lot** of work, and I'd strongly recommend to look for existing solutions (unless "the journey is the reward"). For example, there is https://github.com/ModularMods/MCglTF - they seem to have inlined a lot of the JglTF source code, which is ... 😑  meh... but it might be an easier solution if you just want to load a glTF file...

**Comment by RexBluefox** [comment]
ok. thanks its beginning to look more like a cat. now the next part is rotation and scale and translation. where is that stored?

the cat (x & y scaled by 10000):
![image](https://github.com/javagl/JglTF/assets/53141624/e36a23b9-4070-49cc-b5b8-f5c52769881f)

**Comment by RexBluefox** [comment]
> > i changed the model that is loaded from the duck to the cat and all the vertices have coordinates at the 2nd decimal point or even less. is that normal?
> 
> The vertex coordinates are only the vertex coordinates that are stored in the accessor. They will still be affected by the transforms of the nodes that refer to the respective mesh. For example, a vertex coordinate (1,2,3) may be part of a mesh that is attached to a node that has a `translation` of `10,20,30`, and the vertex will end up at (11,22,33). It may also be attached to a node that has a `scale` of `0.1,0.1,0.1`, so that the vertex will end up at (0.1, 0.2, 0.3).
> 
> If your goal is to write a full-fledged "glTF renderer in Minecraft", then you'll have to invest **a lot** of work, and I'd strongly recommend to look for existing solutions (unless "the journey is the reward"). For example, there is https://github.com/ModularMods/MCglTF - they seem to have inlined a lot of the JglTF source code, which is ... 😑 meh... but it might be an easier solution if you just want to load a glTF file...

and btw the journey is part of the reward yeah

**Comment by javagl** [comment]
> now the next part is rotation and scale and translation. where is that stored?

The [Scenes and Nodes](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_004_ScenesNodes.md) section of the tutorial should cover this pretty well. Each node can have a `matrix` property, or `scale`, `translation`, `rotation` properties from which a matrix can be computed. The product of all matrices (from the root to the node that contains the mesh) is the transform that is applied to the vertex positions.

**Comment by RexBluefox** [comment]
ok. i read through the article and now im done with that.
The next **big** thing is textures/materials.
I also read through the article about that but as it seems the MaterialMode isnt implemented right now, right?
Because its just an empty class.
So i have to go over the TextureModels. but how do i do that. to be precise: how do i associate a texture with a mesh?

**Comment by javagl** [comment]
The 'material' topic is ... a bit complicated, and some sort of 'quirk' in JglTF.

Trying to summarize: 

In glTF 1.0, there was a concept of 'materials' that was _completely_ unrelated to the PBR materials that have been introduced with glTF 2.0. (In fact, creating and standardizing a common PBR material model was one of the most important aspects of defining glTF 2.0). But still, when I started JglTF, I always had the goal of supporting both, glTF 1.0 and glTF 2.0. (In hindsight, that was not so clever. Some aspects could be solved _much_ more cleanly and _much_ more easily if all this was tailored only for glTF 2.0...)

So... the `MaterialModel` interface is empty, because there is a `MaterialModelV1` class for glTF 1.0, and a `MaterialModelV2` class for glTF 2.0, and ... they don't have anything in common.

When you fetch a `MaterialModel` from a primitive, you have to (check whether it is a glTF 2.0 material - but nowadays, this is basically _always_ the case, and then) cast it to `MaterialModelV2`:
```
MaterialModel materialModel = meshPrimitiveModel.getMaterialModel();
if (materialModel instanceof MaterialModelV2) {
    MaterialModelV2 materialModelV2 = (MaterialModelV2)materialModel;
    // work with materialModelV2 here...
}
```
There may be multiple textures in a material, but the "most important" one is the base color texture, which is stored as `materialModelV2.getBaseColorTexture()`.

**Comment by RexBluefox** [comment]
Thanks. the rendering is pretty much done now. at first i had some issue because there where red dots on the texture
![Screenshot 2023-10-26 163236](https://github.com/javagl/JglTF/assets/53141624/27f86090-21a9-4262-b57e-95c9c5d5f641)
but its got fixed by setting the the shader program to position_texture_color which let me define a color with each vertex and i just set it to white (255,255,255,255)

**Comment by RexBluefox** [comment]
that i found out by playing around with settings in blender

**Comment by javagl** [comment]
Sooo.... when this is resolved for now (and considering that "GitHub issues" are not "support threads" anyhow...), I think this can be closed.

**Comment by RexBluefox** [comment]
yeah
